# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  #push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install pytest
        if [ -f tf-requirements.txt ]; then pip install -r tf-requirements.txt; fi
    #- name: Test with pytest
    #  run: |
    #    pytest
    - name: Run machine learning
      run: |
          wget -q https://gqqnbig.me/dataset.7z
          7za x -odataset -bso0 -bsp0 dataset.7z
          python3 -O ml.py --size-limit-kb 1 --no-progress --log error dataset | tee output
    - name: Comment on PR
      uses: harupy/comment-on-pr@c0522c44600040927a120b9309b531e3cb6f8d48
      if: ${{ github.event_name == 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: ../../output
    
